<?php
class PMU_Debug extends PMU_Class {

	public function __construct() {
		add_filter( 'permalink_updator_sections', array($this, 'add_debug_section'), 4 );
	}

	public function add_debug_section($admin_sections) {
		$admin_sections['debug'] = array(
			'name'				=>	__('Debug', 'permalink-updator'),
			'function'    => array('class' => 'PMU_Debug', 'method' => 'output')
		);

		return $admin_sections;
	}

	public function output() {
		global $puUpdatorOptions, $puUris, $puPermastructs, $puRedirects, $puExternalRedirects, $wp_filter;

		$debug_section_url = PMU_Admin_Functions::get_admin_url('&section=debug');

		$sections_and_fields = apply_filters('permalink_updator_debug_fields', array(
			'debug-data' => array(
				'section_name' => __('Debug data', 'permalink-updator'),
				'fields' => array(
					'uris' => array(
						'type' => 'textarea',
						'description' => sprintf('%s<br /><strong><a class="pm-confirm-action" href="%s&remove-permalink-updator-settings=uris">%s</a></strong>',
							__('List of the URIs generated by this plugin.', 'permalink-updator'),
							$debug_section_url,
							__('Remove all custom permalinks', 'permalink-updator')
						),
						'label' => __('Array with URIs', 'permalink-updator'),
						'input_class' => 'short-textarea widefat',
						'value' => ($puUris) ? print_r($puUris, true) : ''
					),
					'custom-redirects' => array(
						'type' => 'textarea',
						'description' => sprintf('%s<br /><strong><a class="pm-confirm-action" href="%s&remove-permalink-updator-settings=redirects">%s</a></strong>',
							__('List of custom redirects set-up by this plugin.', 'permalink-updator'),
							$debug_section_url,
							__('Remove all custom redirects', 'permalink-updator')
						),
						'label' => __('Array with redirects', 'permalink-updator'),
						'input_class' => 'short-textarea widefat',
						'value' => ($puRedirects) ? print_r($puRedirects, true) : ''
					),
					'external-redirects' => array(
						'type' => 'textarea',
						'description' => sprintf('%s<br /><strong><a class="pm-confirm-action" href="%s&remove-permalink-updator-settings=external-redirects">%s</a></strong>',
							__('List of external redirects set-up by this plugin.', 'permalink-updator'),
							$debug_section_url, __('Remove all external redirects', 'permalink-updator')
						),
						'label' => __('Array with external redirects', 'permalink-updator'),
						'input_class' => 'short-textarea widefat',
						'value' => ($puExternalRedirects) ? print_r(array_filter($puExternalRedirects), true) : ''
					),
					'permastructs' => array(
						'type' => 'textarea',
						'description' => sprintf('%s<br /><strong><a class="pm-confirm-action" href="%s&remove-permalink-updator-settings=permastructs">%s</a></strong>',
							__('List of permastructures set-up by this plugin.', 'permalink-updator'),
							$debug_section_url,
							__('Remove all permastructures settings', 'permalink-updator')
						),
						'label' => __('Array with permastructures', 'permalink-updator'),
						'input_class' => 'short-textarea widefat',
						'value' => ($puPermastructs) ? print_r($puPermastructs, true) : ''
					),
					'settings' => array(
						'type' => 'textarea',
						'description' => sprintf('%s<br /><strong><a class="pm-confirm-action" href="%s&remove-permalink-updator-settings=settings">%s</a></strong>',
							__('List of plugin settings.', 'permalink-updator'),
							$debug_section_url,
							__('Remove all plugin settings', 'permalink-updator')
						),
						'label' => __('Array with settings used in this plugin.', 'permalink-updator'),
						'input_class' => 'short-textarea widefat',
						'value' => print_r($puUpdatorOptions, true)
					)
				)
			)
		));

		// Now get the HTML output
		$output = '';
		foreach($sections_and_fields as $section_id => $section) {
			$output .= (isset($section['section_name'])) ? "<h3>{$section['section_name']}</h3>" : "";
			$output .= (isset($section['description'])) ? "<p class=\"description\">{$section['description']}</p>" : "";
			$output .= "<table class=\"form-table fixed-table\">";

			// Loop through all fields assigned to this section
			foreach($section['fields'] as $field_id => $field) {
				$field_name = "{$section_id}[$field_id]";
				$field['container'] = 'row';

				$output .= PMU_Admin_Functions::generate_option_field($field_name, $field);
			}

			// End the section
			$output .= "</table>";

		}

		return $output;
	}

}
